[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.24"
optimizer = true
optimizer_runs = 2000
evm_version = "paris"
fs_permissions = [{ access = "read", path = "./"}]

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
lisk_sepolia = "https://rpc.sepolia-api.lisk.com"
lisk_mainnet = "https://rpc.api.lisk.com"

[etherscan]
lisk_sepolia = { key = "no-key-needed", url = "https://sepolia-blockscout.lisk.com/api", chain = 4202 }


[blockscout]
lisk_sepolia = { url = "https://sepolia-blockscout.lisk.com/api", chain = 4202 }